name: build_and_push

on:
  push:
    branches:
      - main

permissions:
  packages: write
  contents: read

env:
  IMAGE_NAME: ghcr.io/muhammadsatriap/lapor-sadang-serang

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug secrets
        run: |
          echo "SUPABASE_URL set: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL != '' }}"
          echo "SUPABASE_ANON_KEY set: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY != '' }}"
          echo "SERVER_IP set: ${{ secrets.SERVER_IP != '' }}"
          echo "SSH_PRIVATE_KEY set: ${{ secrets.SSH_PRIVATE_KEY != '' }}"

      - name: Build and push image
        run: |
          docker build \
            --build-arg NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }} \
            --build-arg NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }} \
            -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:latest

      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          USER: ubuntu
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key $USER@$SERVER_IP "
            echo 'IMAGE_NAME=$IMAGE_NAME' >> /tmp/env_vars
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            docker pull $IMAGE_NAME:latest
            docker stop lapor-sadang-serang || true
            docker rm lapor-sadang-serang || true
            docker run -d --name lapor-sadang-serang -p 3000:3000 \
              -e NEXT_PUBLIC_SUPABASE_URL='${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}' \
              -e NEXT_PUBLIC_SUPABASE_ANON_KEY='${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}' \
              -e PORT=3000 \
              $IMAGE_NAME:latest
          "