name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files to server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_IP }} "
            mkdir -p ~/lapor-sadang-serang"
          scp -o StrictHostKeyChecking=no -r ./* ubuntu@${{ secrets.SERVER_IP }}:~/lapor-sadang-serang/

      - name: Build + Run Docker on server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_IP }} "
            cd ~/lapor-sadang-serang &&
            docker build -t lapor-sadang-serang . &&
            docker stop lapor-sadang-serang || true &&
            docker rm lapor-sadang-serang || true &&
            docker run -d --name lapor-sadang-serang -p 3000:3000 \
              -e NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }} \
              -e NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }} \
              lapor-sadang-serang
          "
