name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -t lapor-sadang-serang .

    - name: Save Docker image to tar.gz
      run: |
        docker save lapor-sadang-serang | gzip > lapor-sadang-serang.tar.gz

    - name: Upload image to EC2
      run: |
        scp -o StrictHostKeyChecking=no -i /tmp/id_rsa lapor-sadang-serang.tar.gz ubuntu@${{ secrets.SERVER_IP }}:~/

      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
      shell: bash

    - name: Deploy on EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker load < lapor-sadang-serang.tar.gz
          docker stop lapor-app || true
          docker rm lapor-app || true
          docker run -d --name lapor-app -p 3000:3000 lapor-sadang-serang
